### ISSUE TITLE
department

### ISSUE THREAD

**Issue by michaelortnersanube** [captainqwerty/AutomatedOutlookSignature#11]
Hello,

is it possible to insert "department", what i have to insert? Thanks for your help!

**Comment by captainqwerty** [comment]
Hello, yes it's very easy to add.

if($user.Department.count -gt 0){$department = $user.Department[0]} # Department

You need the above with the other variables being set
and then just add it to the HTML similar to the way the other items have been done.

I will build department into my example and my code tonight, so others have the choice as well.

Thank you.

I will leave this ticket open until I have done it.

**Comment by michaelortnersanube** [comment]
Thank you so much for your help :)
