### ISSUE TITLE
Dispose of [adsisearcher]

### ISSUE THREAD

**Issue by Toxicterror** [captainqwerty/AutomatedOutlookSignature#14]
DirectorySearchers should be disposed after using. 
_Set-OutlookSignature.Ps1, Line 23_

See here:
https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.directorysearcher.findall?view=dotnet-plat-ext-7.0#remarks

**Comment by captainqwerty** [comment]
Thank you. I shall implement that tonight.

**Comment by captainqwerty** [comment]
@Toxicterror  so looking into this, I cannot seem to call $user.Dispose() and when I look the remark only appears on .FindAll() not on .FindOne() which I am using.

**Comment by Toxicterror** [comment]
You are absolutely right! I am sorry for any inconveniences.

There's no remark on the microsoft page either:
https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.directorysearcher.findone?view=dotnet-plat-ext-7.0#system-directoryservices-directorysearcher-findone
